[package]
name = "APTpay"
version = "1.0.0"
authors = ["APTpay Team"]
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/move-stdlib"

[addresses]
aptpay = "0x7ccdab8fecaff6c2954dedcf2c82fcdf9eefd369f105ca45c1897b783bd2202b"
std = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"